# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login_form.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LogInSignUpForm(object):
    def setupUi(self, LogInSignUpForm):
        LogInSignUpForm.setObjectName("LogInSignUpForm")
        LogInSignUpForm.resize(289, 200)
        LogInSignUpForm.setMinimumSize(QtCore.QSize(289, 200))
        LogInSignUpForm.setMaximumSize(QtCore.QSize(289, 200))
        LogInSignUpForm.setFocusPolicy(QtCore.Qt.NoFocus)
        LogInSignUpForm.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(LogInSignUpForm)
        self.centralwidget.setObjectName("centralwidget")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(4, 3, 281, 191))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_login = QtWidgets.QLabel(self.layoutWidget)
        self.label_login.setMinimumSize(QtCore.QSize(0, 0))
        self.label_login.setStyleSheet("background-color: #aaaddd")
        self.label_login.setObjectName("label_login")
        self.verticalLayout.addWidget(self.label_login)
        self.lineEdit_login = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_login.setObjectName("lineEdit_login")
        self.verticalLayout.addWidget(self.lineEdit_login)
        self.label_password = QtWidgets.QLabel(self.layoutWidget)
        self.label_password.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_password.setStyleSheet("background-color: #aaaddd")
        self.label_password.setObjectName("label_password")
        self.verticalLayout.addWidget(self.label_password)
        self.lineEdit_password = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_password.setObjectName("lineEdit_password")
        self.verticalLayout.addWidget(self.lineEdit_password)
        self.btn_login = QtWidgets.QPushButton(self.layoutWidget)
        self.btn_login.setAutoRepeat(False)
        self.btn_login.setObjectName("btn_login")
        self.verticalLayout.addWidget(self.btn_login)
        self.btn_signup = QtWidgets.QPushButton(self.layoutWidget)
        self.btn_signup.setObjectName("btn_signup")
        self.verticalLayout.addWidget(self.btn_signup)
        LogInSignUpForm.setCentralWidget(self.centralwidget)

        self.retranslateUi(LogInSignUpForm)
        QtCore.QMetaObject.connectSlotsByName(LogInSignUpForm)

    def retranslateUi(self, LogInSignUpForm):
        _translate = QtCore.QCoreApplication.translate
        LogInSignUpForm.setWindowTitle(_translate("LogInSignUpForm", "Login"))
        self.label_login.setText(_translate("LogInSignUpForm", "Login"))
        self.label_password.setText(_translate("LogInSignUpForm", "Password"))
        self.btn_login.setText(_translate("LogInSignUpForm", "Log in"))
        self.btn_signup.setText(_translate("LogInSignUpForm", "Sign up"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    LogInSignUpForm = QtWidgets.QMainWindow()
    ui = Ui_LogInSignUpForm()
    ui.setupUi(LogInSignUpForm)
    LogInSignUpForm.show()
    sys.exit(app.exec_())
