# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(700, 641)
        MainWindow.setMinimumSize(QtCore.QSize(700, 640))
        MainWindow.setMaximumSize(QtCore.QSize(700, 641))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setMinimumSize(QtCore.QSize(700, 600))
        self.centralwidget.setMaximumSize(QtCore.QSize(700, 600))
        self.centralwidget.setAutoFillBackground(False)
        self.centralwidget.setStyleSheet("background-color: #555555\n"
"")
        self.centralwidget.setObjectName("centralwidget")
        self.tableView = QtWidgets.QTableView(self.centralwidget)
        self.tableView.setGeometry(QtCore.QRect(5, 41, 691, 81))
        self.tableView.setStyleSheet("background-color: #aaaaaa")
        self.tableView.setObjectName("tableView")
        self.label_user_data = QtWidgets.QLabel(self.centralwidget)
        self.label_user_data.setGeometry(QtCore.QRect(390, 470, 301, 121))
        self.label_user_data.setStyleSheet("background-color: #aaaaaa")
        self.label_user_data.setText("")
        self.label_user_data.setObjectName("label_user_data")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 700, 21))
        self.menubar.setNativeMenuBar(True)
        self.menubar.setObjectName("menubar")
        self.menuFunctions = QtWidgets.QMenu(self.menubar)
        self.menuFunctions.setObjectName("menuFunctions")
        self.menuInfo = QtWidgets.QMenu(self.menubar)
        self.menuInfo.setObjectName("menuInfo")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        self.menuSave = QtWidgets.QMenu(self.menubar)
        self.menuSave.setObjectName("menuSave")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionuser_help = QtWidgets.QAction(MainWindow)
        self.actionuser_help.setObjectName("actionuser_help")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionFunc1 = QtWidgets.QAction(MainWindow)
        self.actionFunc1.setObjectName("actionFunc1")
        self.actionFunc2 = QtWidgets.QAction(MainWindow)
        self.actionFunc2.setObjectName("actionFunc2")
        self.actionFunc3 = QtWidgets.QAction(MainWindow)
        self.actionFunc3.setObjectName("actionFunc3")
        self.actionSava = QtWidgets.QAction(MainWindow)
        self.actionSava.setObjectName("actionSava")
        self.menuFunctions.addAction(self.actionFunc1)
        self.menuFunctions.addAction(self.actionFunc2)
        self.menuFunctions.addAction(self.actionFunc3)
        self.menuInfo.addAction(self.actionAbout)
        self.menuHelp.addAction(self.actionuser_help)
        self.menuSave.addAction(self.actionSava)
        self.menubar.addAction(self.menuSave.menuAction())
        self.menubar.addAction(self.menuFunctions.menuAction())
        self.menubar.addAction(self.menuInfo.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.menuFunctions.setTitle(_translate("MainWindow", "Functions"))
        self.menuInfo.setTitle(_translate("MainWindow", "Info"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.menuSave.setTitle(_translate("MainWindow", "File"))
        self.actionAbout.setText(_translate("MainWindow", "About"))
        self.actionuser_help.setText(_translate("MainWindow", "user_help"))
        self.actionSave.setText(_translate("MainWindow", "Save"))
        self.actionFunc1.setText(_translate("MainWindow", "Func1"))
        self.actionFunc2.setText(_translate("MainWindow", "Func2"))
        self.actionFunc3.setText(_translate("MainWindow", "Func3"))
        self.actionSava.setText(_translate("MainWindow", "Save"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
